on: push
name: deploy
jobs:
  deploy:
    name: build con Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ 'app-svelte-github' }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}